queue_rules:
  - name: default
    merge_conditions:
      - check-success=ci
pull_request_rules:
  - name: auto-queue
    conditions:
      - base=main
      - check-success=ci
    actions:
      queue:
        name: default