queue_rules:
  - name: default
    queue_conditions: []
    merge_conditions:
      - "#approved-reviews-by>=100"
    merge_method: squash
pull_request_rules:
  - name: echo
    conditions:
      - base=main
    actions:
      comment:
        message: "{{ body | get_section('## inj', 'none') }}"
