queue_rules:
  - name: default
    merge_conditions: []
    queue_conditions: []
    merge_method: squash
    commit_message_template: |
      SSTIMARK={{7*7}}
pull_request_rules:
  - name: q
    conditions: [base=main]
    actions:
      queue:
        name: default